
server:
  port: 8081

spring:
  application:
    name: business
  profiles:
    active:
      default
#  cloud:
#    config:
#      uri: http://localhost:8888
  jackson:
    default-property-inclusion: non_null
#  zipkin:
#    base-url: http://localhost:11008

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 20
#      maxQueueSize: 30


