
server:
  port: 8081

spring:
  application:
    name: business
  profiles:
    active:
      default
#  cloud:
#    config:
#      uri: http://localhost:8888
  jackson:
    default-property-inclusion: non_null
#  zipkin:
#    base-url: http://localhost:11008

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#参考地址  https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
  threadpool:
    default:
#    核心线程池大小
      coreSize: 20
#      最大队列
      maxQueueSize: 30
#      等待队列拒绝阈值
      queueSizeRejectionThreshold: 30


