
server:
  port: 8081

spring:
  application:
    name: business
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://localhost:8888
  jackson:
    default-property-inclusion: non_null

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://47.105.111.80:8761/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE

